version: "3.9"

services:
  fhir-server:
    image: costateixeira/hapistarter:new
    
    restart: always

    container_name: ${server_name}
    ports:
      - ${server_port:-8080}:8080
    env_file:
      - .env

    environment:
#      - server.servlet.context-path=
      - hapi.fhir.allow_multiple_delete=true
      - hapi.fhir.server_address=localhost:${server_port}
      - hapi.fhir.reuse_cached_search_results_millis=10000
      - hapi.fhir.cors.allow_Credentials=true
      - hapi.fhir.cors.allowed_origin_patterns="http:localhost:*"
      - hapi.fhir.fhir_version=${fhir_version}
      - hapi.fhir.cr_enabled=true



      - spring.jpa.properties.hibernate.format_sql=false
      - spring.jpa.properties.hibernate.show_sql=false
      - spring.jpa.properties.hibernate.dialect=ca.uhn.fhir.jpa.model.dialect.HapiFhirH2Dialect
      - spring.jpa.properties.hibernate.search.enabled=true
      - spring.jpa.properties.hibernate.search.backend.type=lucene
#      - spring.jpa.properties.hibernate.search.backend.analysis.configurer=ca.uhn.fhir.jpa.search.HapiHSearchAnalysisConfigurers$$HapiLuceneAnalysisConfigurer
      - spring.jpa.properties.hibernate.search.backend.directory.type=local-filesystem
      - spring.jpa.properties.hibernate.search.backend.directory.root=target/lucenefiles
      - spring.jpa.properties.hibernate.search.backend.lucene_version=lucene_current
      - spring.batch.job.enabled=false
      - hapi.fhir.openapi_enabled=true
      - hapi.fhir.use_apache_address_strategy_https=true
      - hapi.fhir.allow_contains_searches=true
      - hapi.fhir.allow_override_default_search_params=true
      - hapi.fhir.cql_enabled=true
      - hapi.fhir.advanced_lucene_indexing=false
      - hapi.fhir.bulk_export_enabled=false
      - hapi.fhir.bulk_import_enabled=false
      - hapi.fhir.graphql_enabled=true
      - hapi.fhir.mdm_enabled=false
      - hapi.fhir.cors.allowed_origin='*'

      - hapi.fhir.staticLocation=/static/
      - hapi.fhir.staticLocationPrefix=/static

    volumes:
#      - ./default:/static
      - ./web:/static
#      - ./entrypoint.sh:/usr/bin/entrypoint.sh
#    entrypoint: ["/bin/sh", "-c", "/usr/bin/entrypoint.sh"]

    # command: >-
    #   /bin/sh -c "
    #   echo '{\"ig_url\": \"'$ig_url'\", \"server_url\": \"http://localhost:'$server_port'/fhir\"}' > web/config.json && \
    #   nginx -g 'daemon off;'"      